In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor
from sklearn.preprocessing import StandardScaler

In [11]:
df = pd.read_csv('Resources/uswhites.csv')

In [12]:
df = df.drop(['ID', 'category', 'country', 'description', 'designation', 'subsubregion', 'title', 'url', 'winery'], axis=1)
df.head()


alcohol  price  rating      region          subregion  \
0     14.1   50.0      94  California             Sonoma   
1     12.6   30.0      94      Oregon  Willamette Valley   
2     13.8   60.0      94  California        Napa-Sonoma   
3     13.8   35.0      94  Washington    Columbia Valley   
4     14.7   65.0      94  California             Sonoma   

                     varietal  vintage  
0                  Chardonnay     2016  
1                    Riesling     2016  
2                  Chardonnay     2016  
3  Bordeaux-style White Blend     2017  
4                  Chardonnay     2016

In [13]:
X_df = pd.DataFrame(df)
X_df = df.drop("price", axis=1)
X_df['subregion'] = X_df['subregion'].astype(str)
X_df['vintage'] = X_df['vintage'].astype(int)
y = df["price"]
X_df.dtypes

alcohol      float64
rating         int64
region        object
subregion     object
varietal      object
vintage        int32
dtype: object

In [14]:
from sklearn.preprocessing import LabelEncoder
X = X_df.apply(LabelEncoder().fit_transform)
X

alcohol  rating  region  subregion  varietal  vintage
0          130      14       2         42        17       22
1           68      14      17         56        87       22
2          118      14       2         28        17       22
3          118      14      24          7        10       23
4          152      14       2         42        17       22
...        ...     ...     ...        ...       ...      ...
23653      147      11       2          3        17       11
23654      147      12       2          3        17       11
23655      159      12       2          3        17       11
23656      176      12       2         42       138       10
23657      139      12       2          2        17       11

[23658 rows x 6 columns]

In [15]:
X = X.values.astype("float32")
print(X)
y = y.values.astype("float32")
print(y)


[[130.  14.   2.  42.  17.  22.]
 [ 68.  14.  17.  56.  87.  22.]
 [118.  14.   2.  28.  17.  22.]
 ...
 [159.  12.   2.   3.  17.  11.]
 [176.  12.   2.  42. 138.  10.]
 [139.  12.   2.   2.  17.  11.]]
[50. 30. 60. ... 29. 24. 55.]


In [16]:
#SHOULD SCALE PROBABLY???

In [17]:
input_dims = X.shape[1]

In [18]:
def create_model(optimizer='rmsprop', init='glorot_uniform'):
    model = Sequential()
    model.add(Dense(12, input_dim=input_dims, kernel_initializer=init, activation='relu'))
    model.add(Dense(8, input_dim=input_dims, kernel_initializer=init, activation='relu'))
    model.add(Dense(1, kernel_initializer=init))
    model.compile(loss='mean_squared_error', optimizer=optimizer, metrics=['accuracy'])
    return model

In [21]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
model = KerasRegressor(build_fn=create_model, verbose=0)
# grid search epochs, batch size and optimizer
optimizers = ['rmsprop', 'adam']
init = ['glorot_uniform','normal','uniform']
epochs = [50, 100, 150]
batches = [5, 10, 20]
param_grid = dict(optimizer=optimizers, epochs=epochs, batch_size=batches, init=init)
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid_result = grid.fit(X, y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
	print("%f (%f) with: %r" % (mean, stdev, param))              

Using TensorFlow backend.
C:\Users\koegs\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best: -87.747733 using {'batch_size': 10, 'epochs': 100, 'init': 'glorot_uniform', 'optimizer': 'adam'}
-93.204869 (5.843310) with: {'batch_size': 5, 'epochs': 50, 'init': 'glorot_uniform', 'optimizer': 'rmsprop'}
-90.143662 (4.693365) with: {'batch_size': 5, 'epochs': 50, 'init': 'glorot_uniform', 'optimizer': 'adam'}
-91.915675 (4.947121) with: {'batch_size': 5, 'epochs': 50, 'init': 'normal', 'optimizer': 'rmsprop'}
-92.844608 (9.064854) with: {'batch_size': 5, 'epochs': 50, 'init': 'normal', 'optimizer': 'adam'}
-92.522123 (7.878285) with: {'batch_size': 5, 'epochs': 50, 'init': 'uniform', 'optimizer': 'rmsprop'}
-93.890970 (7.270158) with: {'batch_size': 5, 'epochs': 50, 'init': 'uniform', 'optimizer': 'adam'}
-91.242589 (3.738749) with: {'batch_size': 5, 'epochs': 100, 'init': 'glorot_uniform', 'optimizer': 'rmsprop'}
-88.942145 (3.944426) with: {'batch_size': 5, 'epochs': 100, 'init': 'glorot_uniform', 'optimizer': 'adam'}
-92.789928 (3.610481) with: {'batch_size': 5, 'epochs': 