In [35]:

import pandas as pd
import pandas
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
import sqlalchemy as sa

In [36]:
wine_db = "postgresql://postgres:postgres@localhost:5432/Final"
engine = sa.create_engine(wine_db, echo=False)
conn = engine.connect()

In [37]:
df = pd.read_sql("SELECT * FROM all_wines", conn)

In [38]:
df.head()

ID  alcohol category  country  \
0   1     13.2      Red       US   
1   2     15.0      Red    Italy   
2   3     14.1      Red       US   
3   4     14.1    White       US   
4   5     13.5    White  Austria   

                                         description  \
0  This is among winemaker Cathy Corison's finest...   
1  Enticing scents of spiced plum, pipe tobacco, ...   
2  Bright, crunchy red fruit effuses ripeness in ...   
3  This white has an expert level of intensity an...   
4  Yeast, celery and a hint of cream make for an ...   

                         designation  price  rating      region  \
0                    Kronos Vineyard  185.0      95  California   
1          Vigneto Monte Sant'Urbano   80.0      94      Veneto   
2                      Foss Vineyard   62.0      94  California   
3  Dutton Ranch Walker Hill Vineyard   50.0      94  California   
4                            Spiegel   34.0      94      Wagram   

                             subregion          subsubregion  \
0                                 Napa            St. Helena   
1  Amarone della Valpolicella Classico                  None   
2                               Sonoma  Russian River Valley   
3                               Sonoma          Green Valley   
4                                 None                  None   

                                               title  \
0  Corison 2015 Kronos Vineyard Cabernet Sauvigno...   
1  Speri 2013 Vigneto Monte Sant'Urbano  (Amarone...   
2  Williams Selyem 2016 Foss Vineyard Pinot Noir ...   
3  Dutton-Goldfield 2016 Dutton Ranch Walker Hill...   
4  Anton Bauer 2017 Spiegel Grüner Veltliner (Wag...   

                                                 url            varietal  \
0  https://www.winemag.com/buying-guide/corison-2...  Cabernet Sauvignon   
1  https://www.winemag.com/buying-guide/speri-201...           Red Blend   
2  https://www.winemag.com/buying-guide/williams-...          Pinot Noir   
3  https://www.winemag.com/buying-guide/dutton-go...          Chardonnay   
4  https://www.winemag.com/buying-guide/anton-bau...    Grüner Veltliner   

   vintage            winery  
0   2015.0           Corison  
1   2013.0             Speri  
2   2016.0   Williams Selyem  
3   2016.0  Dutton-Goldfield  
4   2017.0       Anton Bauer

In [39]:
df = df.drop(['ID', 'alcohol', 'description', 'designation', 'title', 'url', 'vintage','winery'], axis=1)
df.head()

category  country  price  rating      region  \
0      Red       US  185.0      95  California   
1      Red    Italy   80.0      94      Veneto   
2      Red       US   62.0      94  California   
3    White       US   50.0      94  California   
4    White  Austria   34.0      94      Wagram   

                             subregion          subsubregion  \
0                                 Napa            St. Helena   
1  Amarone della Valpolicella Classico                  None   
2                               Sonoma  Russian River Valley   
3                               Sonoma          Green Valley   
4                                 None                  None   

             varietal  
0  Cabernet Sauvignon  
1           Red Blend  
2          Pinot Noir  
3          Chardonnay  
4    Grüner Veltliner

In [40]:
df = df.dropna(subset=['subsubregion'])
df = df.dropna(subset=['subregion'])

In [41]:
df

category country  price  rating      region          subregion  \
0           Red      US  185.0      95  California               Napa   
2           Red      US   62.0      94  California             Sonoma   
3         White      US   50.0      94  California             Sonoma   
10          Red      US   62.0      93      Oregon  Willamette Valley   
11          Red      US   62.0      93      Oregon  Willamette Valley   
...         ...     ...    ...     ...         ...                ...   
192038      Red      US   80.0      92  California   Sierra Foothills   
192041    White      US   29.0      92  California      Central Coast   
192043    White      US   24.0      92  California             Sonoma   
192044    White      US   55.0      92  California   California Other   
192045      Red      US   30.0      92  California      Central Coast   

                subsubregion            varietal  
0                 St. Helena  Cabernet Sauvignon  
2       Russian River Valley          Pinot Noir  
3               Green Valley          Chardonnay  
10         Willamette Valley          Pinot Noir  
11           Yamhill-Carlton          Pinot Noir  
...                      ...                 ...  
192038      Sierra Foothills               Syrah  
192041  Santa Barbara County          Chardonnay  
192043      Alexander Valley           Zinfandel  
192044            California          Chardonnay  
192045         Central Coast        Petite Sirah  

[81516 rows x 8 columns]

In [42]:
# X_df = pd.DataFrame(df)
# X_df['subregion'] = X_df['subregion'].astype(str)

In [43]:
X = df.drop("price", axis=1)
y = df["price"]

In [44]:
X= X.apply(LabelEncoder().fit_transform)
X

category  country  rating  region  subregion  subsubregion  varietal
0              3        0      15       0          8           223        28
2              3        0      14       0         14           163       161
3              6        0      14       0         14            58        49
10             3        0      13       2         18           244       161
11             3        0      13       2         18           248       161
...          ...      ...     ...     ...        ...           ...       ...
192038         3        0      12       0         13           196       210
192041         6        0      12       0          1           182        49
192043         6        0      12       0         14             1       266
192044         6        0      12       0          0            17        49
192045         3        0      12       0          1            24       147

[81516 rows x 7 columns]

In [45]:
X = X.values.astype("float32")
print(X)
y = y.values.astype("float32")
print(y)

[[  3.   0.  15. ...   8. 223.  28.]
 [  3.   0.  14. ...  14. 163. 161.]
 [  6.   0.  14. ...  14.  58.  49.]
 ...
 [  6.   0.  12. ...  14.   1. 266.]
 [  6.   0.  12. ...   0.  17.  49.]
 [  3.   0.  12. ...   1.  24. 147.]]
[185.  62.  50. ...  24.  55.  30.]


In [46]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, random_state=42)
# print(y_test.shape)
# print(X_test.shape)

In [47]:
scaler_model = StandardScaler()

In [48]:
X_scaler = scaler_model.fit(X)
X_scaled = X_scaler.transform(X)

In [49]:
# y_train=y_train.reshape(-1,1)
# y_test=y_test.reshape(-1,1)

In [50]:
# X_scaler = scaler_model.fit(X_train)
# y_scaler = scaler_model.fit(y_train)

In [51]:
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)
# y_train_scaled = y_scaler.transform(y_train)
# y_test_scaled = y_scaler.transform(y_test)
# y_test_scaled

In [52]:
# input_dims = X_train.shape[1]
input_dims = X.shape[1]
input_dims

7

In [53]:
model = Sequential()

model.add(Dense(12, activation = 'relu', name='dense_1', kernel_initializer='random_uniform', input_dim=(input_dims)))
# model.add(Dropout(0.3))
model.add(Dense(8, activation='relu', name='dense_2', kernel_initializer='random_uniform'))
# model.add(Dropout(0.3))
model.add(Dense(1, name='predictions'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                96        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 104       
_________________________________________________________________
predictions (Dense)          (None, 1)                 9         
Total params: 209
Trainable params: 209
Non-trainable params: 0
_________________________________________________________________


In [54]:
from numpy import sqrt,asarray
model.compile(optimizer='adam', loss='mse', metrics=['mse','mae'])


In [55]:
from keras.callbacks import EarlyStopping

In [56]:
history = model.fit(X, y, epochs=30, callbacks=[EarlyStopping(patience=5)])


Epoch 1/30
81516/81516 [==============================] - 4s 44us/step - loss: 545.0554 - mse: 545.0546 - mae: 14.6418
Epoch 2/30
 5152/81516 [>.............................] - ETA: 3s - loss: 397.8392 - mse: 397.8390 - mae: 12.9954

C:\Users\koegs\Anaconda3\lib\site-packages\keras\callbacks\callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mse,mae
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


81516/81516 [==============================] - 3s 39us/step - loss: 417.9707 - mse: 417.9709 - mae: 12.9037
Epoch 3/30
81516/81516 [==============================] - 3s 42us/step - loss: 407.8734 - mse: 407.8736 - mae: 12.7246
Epoch 4/30
81516/81516 [==============================] - 3s 40us/step - loss: 403.1676 - mse: 403.1679 - mae: 12.6070
Epoch 5/30
81516/81516 [==============================] - 3s 39us/step - loss: 400.3521 - mse: 400.3519 - mae: 12.5392
Epoch 6/30
81516/81516 [==============================] - 3s 37us/step - loss: 397.8782 - mse: 397.8779 - mae: 12.4969
Epoch 7/30
81516/81516 [==============================] - 3s 38us/step - loss: 396.2683 - mse: 396.2686 - mae: 12.4690
Epoch 8/30
81516/81516 [==============================] - 3s 36us/step - loss: 394.2979 - mse: 394.2978 - mae: 12.4419
Epoch 9/30
81516/81516 [==============================] - 3s 38us/step - loss: 393.4899 - mse: 393.4896 - mae: 12.4122
Epoch 10/30
81516/81516 [==============================] - 

In [57]:
print(X[0])
test_data = X[0]
# test_data = scaler_model.inverse_transform(X_train[0])
Npred = (model.predict(test_data.reshape(1,7)))
print(Npred)
print(y[0])

[  3.   0.  15.   0.   8. 223.  28.]
[[114.467834]]
185.0


In [58]:
model.save('model_all_wines_predict.h5')

In [59]:
from tensorflow.keras.models import load_model
old_model = load_model('model_all_wines_predict.h5')

In [60]:
print(X[0])
test_data = X[0]
# test_data = scaler_model.inverse_transform(X_train[0])
Npred = (old_model.predict(test_data.reshape(1,7)))
print(Npred)
print(y[0])

[  3.   0.  15.   0.   8. 223.  28.]
[[114.467834]]
185.0
